name: cicd
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [synchronize, opened, reopened]

jobs:
  test:
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Test cicd
        run: echo "Running only tests"

  upload-artifact:
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - name: pwd
        run: pwd
      - name: upload zip to gh artifacts
        uses: actions/upload-artifact@v4
        with:
          name: go-notes-artifact
          path: /home/runner/work/go-notes

  deploy:
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - name: Deploy cicd
        run: echo "Running only deploy stage"
