name: cicd
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Test cicd
        run: echo "Running only tests"
      - name: Simulate error
        run: |
          echo "oh no error"
          exit 1
  
  deploy:
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - name: Deploy cicd
        run: echo "Running only deploy stage"
