name: cicd
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [synchronize, opened, reopened]

jobs:
  test:
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Test cicd
        run: echo "Running only tests"

  upload-artifact:
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - name: create zip
        run: zip -r go-notes.zip . -x '*.git*'

      - name: upload zip to gh artifacts
        uses: actions/upload-artifact@v4
        with:
          name: go-notes-zip
          path: /

  deploy:
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - name: Deploy cicd
        run: echo "Running only deploy stage"
